joint_1:
  ID: 6
  Return_Delay_Time: 0
joint_2:
  ID: 7
  Return_Delay_Time: 0
joint_3:
  ID: 8
  Return_Delay_Time: 0
joint_4:
  ID: 9
  Return_Delay_Time: 0
# Tool actuator:
joint_5: 
  ID: 10
  Return_Delay_Time: 0